---
name: app_event_service
description: A library to handle multi event callback.
version: 0.0.1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  equatable: ^2.0.3
  meta: ^1.7.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.20.2
  very_good_analysis: ^2.4.0
