---
name: flivver
description: An elegant and clean solution to handling callbacks for custom events.
version: 0.0.1
homepage: https://github.com/Chaitanyabsprip/flivver
repository: https://github.com/Chaitanyabsprip/flivver

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  equatable: ^2.0.3
  meta: ^1.7.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.20.2
  very_good_analysis: ^3.0.2
